[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
# library for end-to-end messaging
# the JSON feature is not automatically included when it comes to Rust
rocket = { version = "0.5.1", features = ["json"] }
rand = "0.8.4"
