name: update
on: push

jobs:
  update:
    name: EAS update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: Expo Github Actions
        uses: expo/expo-github-action@8.2.1

        with:
          eas-version: latest
          token: n5mAjBGWGe3H20wx9Vcp7AN20L1U80WIDVes0Aao

      - name: Install Dependancies
        run: yarn Install

      - name: Publish Update
        run: eas update --auto
